### ISSUE TITLE
error configuration shibboleth

### ISSUE THREAD

**Issue by michel123456789** [toyokazu/omniauth-shibboleth#12]
hi ,,,
at the first i'm configur shibboleth, i get more of problem. i was try a lot of configuration start from CRSDU, KERBEROS, et all but i'm still fail. could u help me to configure shibboleth on ubuntu 12.04 LTS or windows server 2003 & 2008 R2.
thank's

**Comment by toyokazu** [comment]
Please ask Shibboleth related things at shibboleth.net.
Users ML can be used for the purpose.

http://shibboleth.net/community/lists.html
