### ISSUE TITLE
No shibboleth session with Apache-Unicorn

### ISSUE THREAD

**Issue by arrk-shoba** [toyokazu/omniauth-shibboleth#15]
Hello Toyokazu San,

We were earlier using Apache with Passenger and the Shibboleth worked fine. Recently we have switched to Apache with Unicorn for performance reasons. Since then, shibboleth is not working. We are facing "users/auth/failure?message=no_shibboleth_session" in URL every time we try.

Isn't there any way we can get the Shibd-session access with same Apache & Unicorn setup? What changes we might have to do to get this working? Please suggest some way.

regards,
Shoba

**Comment by toyokazu** [comment]
Hi Shoba san,

Sorry to be late reply.
When you use unicorn as a Rails container and you want to add access control function by shibboleth, there are two approaches as written in README.md. The one is as you try, preparing Apache front-end and using proxy function to pass the request to unicorn. In this case, you need to change mod_shib configuration to pass Shibboleth parameters to unicorn via HTTP header by setting 'ShibUseHeaders On'. An example configuration is written in the following section.

https://github.com/toyokazu/omniauth-shibboleth#request_type-option

In this case, you need to understand the things written in the following page.

https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPSpoofChecking

You can also do the similar thing by using rack-saml without Apache.
This approach also has a problem in assertion encryption.

In the both approach, if you understand the points, I think that you can use it in your application.

Best Regards,
Toyokazu

**Comment by arrk-shoba** [comment]
Hello Toyokazu San,

I have updated the Apache config's mod_shib to include 'ShibUseHeaders On' and added ':request_type => :header' in config/initializers/omniauth.rb.
Still I am facing the 'users/auth/failure?message=no_shibboleth_session'.

Do you suggest any other we can get this working?

regards,
Shoba

**Comment by toyokazu** [comment]
Do you already tried :debug => true? It helps to distinguish where is the cause. If you have headers in the  output, the cause resides in omniauth-shibboleth, if not, it resides in apache and mod_shib.

If it resides apache and mod_shib, please ask at Shibboleth community. You can get more appropriate answer.

Anyway, I am not sure the root cause, but if you are using Apache 2.4, Proxy related function may prevent the headers pass through to unicorn. ProxyAddHeaders directive may have some effect.

http://httpd.apache.org/docs/current/en/mod/mod_proxy.html

I have not tested and I am sorry that I cannot make time now...
Please try by yoursef ;)

Best Regards,

**Comment by arrk-shoba** [comment]
Hello Toyokazu San,

The issue is resolved now. 
Modified the Apache vhost config and added the following line:
RewriteCond %{REQUEST_URI} !/Shibboleth.sso
before RewriteRule ^/(.*)$ balancer://unicornservers%{REQUEST_URI} [P,QSA,L]

In config/initializers/omniauth.rb, added :request_type => :header,
    :shib_session_id_field => "HTTP_SHIB_SESSION_ID",
    :shib_application_id_field => "HTTP_SHIB_APPLICATION_ID"

provider :shibboleth, { #:debug => true,
    :request_type => :header,
    :shib_session_id_field => "HTTP_SHIB_SESSION_ID",
    :shib_application_id_field => "HTTP_SHIB_APPLICATION_ID",
    :uid_field => :univ_id,
    :fields => []
  }

In config/initializers/devise.rb, added the :shib_session_id_field => "HTTP_SHIB_SESSION_ID",
    :shib_application_id_field => "HTTP_SHIB_APPLICATION_ID"

config.omniauth :shibboleth, {
    :request_type => :header,
    :shib_session_id_field     => "HTTP_SHIB_SESSION_ID",
    :shib_application_id_field => "HTTP_SHIB_APPLICATION_ID",
    :uid_field => :univ_id,
    :fields => []
  }

Restart apache and unicorn. Now I see the session established.

**Comment by toyokazu** [comment]
Thank you for your report.
It will be helpful for the Shibboleth users :)
