### ISSUE TITLE
handling multiple attribute values from IDP

### ISSUE THREAD

**Issue by matthias-fratz** [toyokazu/omniauth-shibboleth#18]
The current way of handling of multiple attribute values from IDP is at least problematic and IMO should be changed. mod_shib concatenates multi-valued attributes with semicolons before storing them in the request environment, ie. `value1;value2`. omniauth-shibboleth currently just sticks them into the auth hash like that, leaving the application to deal with the problem.

My use case is that in the federation I'm in, IDPs are allowed to send multiple email addresses, and at least our own IDP is configured to actually do it (and I'm not in a position to change that). Thus a user might have an email attribute with two values, eg. `peter.mueller@example.com` and `pm@example.com`. as is, the application ends up getting an email field of `peter.mueller@example.com;pm@example.com`, and promptly refuses login with an "invalid email" message.

IMO we should instead follow the [omniauth auth-hash spec](https://github.com/omniauth/omniauth/wiki/Auth-Hash-Schema) here and provide "the" email address, ie. a single one. I believe the 'correct' way to do this would be to configure mod_shib or shibd to send only a single value for multi-valued attributes attribute, ie. picking one at random. I couldn't find any way to do that, however, and I suspect that it isn't possible because Shibboleth consistently uses the notion that all values of a multi-valued attribute are equal.

My suggestion would be to split multi-valued attributes and pass only one of the values in the auth hash. In my (application-level) workaround I currently simply use the 'first' one (but attribute values aren't considered ordered, so 'the first one' is effectively 'a random one'). For `name_field` and the `info_fields`, picking a random value looks acceptable: It could be a non-preferred email, name etc., but shouldn't introduce any security issues. We could in principle pass all values as an array for the `extra_fields`, but that could cause regressions as it changes the API. For `uid_field`, I'd suggest refusing the login if multiple values are provided, but I'm not entirely sure how to handle that situation.

In case it isn't clear, I'm willing to implement this, but I'm not sure *what* to implement.

**Comment by toyokazu** [comment]
Hi matthias-fratz,

First of all, recently, since I've been apart from the Shibboleth related development, it is difficult to test your request soon. However, your request seems to be realized by using flexible attribute configuration provided by omniauth-shibboleth as described in README.md.

For example, the following example is obtaining the first entry sorted by dictionary order.

```
% vi config/initializer/omniauth.rb
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :shibboleth, {
    :info_fields => {
      :email    => lambda {|request_param| request_param.call('email').split(";").sort[0]}
    }
  }
end
```

How do you think that? I've not tested it. So, I'm not sure it works for you or not. But if you are in hurry, could you try it?

Best Regards

**Comment by matthias-fratz** [comment]
I'm not in a hurry as I have a useable workaround / hack in the app code. It's a third-party app (GitLab) where I'm trying to get away from having to maintain "custom" modifications, so I'm trying to get the cleanest solution possible and have time to implement stuff if necessary.

I have looked into the flexible attribute config feature briefly, but didn't yet consider it because GitLab uses devise and configures its authentication settings in YAML, so I cannot readily use Ruby code for a field. When I change `initializers/devise.rb`, your code does work correctly (thanks!), so it is possible to implement this in GitLab instead. The reason I believe this should be handled in omniauth-shibboleth is that multiple attribute values are a Shibboleth-specific peculiarity, and don't just affect GitLab + Shibboleth.

How about adding an option like `:multiple_values => 'first'` (or "raw", "array" or a lambda) that specifies how to handle multi-valued attributes? That way, most users could just set the option to "first" and could treat Shibboleth like any other Omniauth provider, without having to worry about multiple values. But handling multi-valued attributes would still be possible for those who want to do it themselves. (I'm still not sure what to do about multiple uids, though.)

**Comment by toyokazu** [comment]
Sorry for being late. I understand your situation. It may be better to add an option as you propose. :multiple_values option may be OK. It may take a long time but I'll try to implement it. If you can make a pull request, it is also welcome :)

Best Regards

**Comment by toyokazu** [comment]
Hi matthias-fratz,

I just wrote a prototype implementation of :multi_values option in add_multi_values_option branch.

https://github.com/toyokazu/omniauth-shibboleth/tree/add_multi_values_option

The code is not tested in the real environment. So, if possible, would you try it in your GitLab environment? You can try it by cloning and checking out the branch.

```
git clone https://github.com/toyokazu/omniauth-shibboleth.git
cd omniauth-shibboleth
git checkout add_multi_values_option
rake build
gem install pkg/omniauth-shibboleth-1.3.0.gem
```

Now you can try the latest version 1.3.0 in your environment.
If the implementation works well, I'd like to merge it to master and public gem.

Best Regards

**Comment by toyokazu** [comment]
I forgot to mention but how to use :multi_values option is written in READEME.md of version 1.3.0.

Best

**Comment by matthias-fratz** [comment]
Thanks for the quick implementation! I will test it as soon as possible. My test-GitLab is currently stuck in a partial migration but I should have it ready for testing by tomorrow.

I believe the split should be done as `split(/(?<!\\);/)` (Ruby ≥1.9.3) or equivalent because, according to [the docs](https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPAttributeAccess), semicolons in attribute values are escaped with a backslash. As far as I can tell from [the shibd 2.6.0 code](https://github.com/craigpg/shibboleth-sp2/blob/master/shibsp/ServiceProvider.cpp#L444) (that's 2.3 but it's the same code in 2.6), nothing else is escaped, not even backslashes. (So I guess attribute values better not end with a backslash.)

**Comment by toyokazu** [comment]
Thank you for your quick feedback! I've updated the code (:first) and the test (examples). As written in README.md and test code, you need to specify escaped backslash like  `split(/(?<!\\\\);/)` for using a String form lambda description. Please try the latest code.

**Comment by matthias-fratz** [comment]
Looks perfect. Omitting the option or setting it to `raw` gives the expected "invalid email" error. Setting it to `first` gives the first email; `lambda {|param_value| param_value.nil? ? nil : param_value.split(/(?<!\\\\);/).sort.reverse[0]}` gives the other one (which happens to be the lexicographically last one thus the `.reverse`).

As for escaping, either of the following two works in my `config.yml`, while cutting the number of backslashes in half gives an "end pattern with unmatched parenthesis" error. (Not quoting the string in YAML obviously prevents GitLab from starting.)

```yaml
  multi_values: "lambda {|param_value| param_value.nil? ? nil : param_value.split(/(?<!\\\\);/).sort.reverse[0]}"
  multi_values: 'lambda {|param_value| param_value.nil? ? nil : param_value.split(/(?<!\\);/).sort.reverse[0]}'
```

(I didn't test configuring in Ruby code, but it's clear why it needs 4 backslashes.)


One thing that I found is that the escaped semicolons themselves are never unescaped even thought the split is correct. (I completely forgot about that corner case in my workaround, which is where the split regex came from.) I guess strictly speaking the resulting value should be postprocessed with `.gsub('\\;', ';')`, and the testcases should check for 'test1;hoge@example.com' instead.

Unfortunately I cannot really test this beyond the basic multiple attributes case. Our IDP produces multiple values but none containing semicolons. I could of course simulate attribute values but as far as I can see that wouldn't accomplish anything the testcases don't already cover.

**Comment by toyokazu** [comment]
Thank you for testing!
I added `.gsub('\\;', ';')` to the :first option code and change test cases from 'test1\;hoge@example.com' to 'test1;hoge@example.com'.
Is that what you mean?
If it is OK, I'd like to merge it to master and gem.
I think that it is difficult to test everything ;) So, if someone really requires that case, I guess that he/she will provide test results in their real environment :)

Best

**Comment by matthias-fratz** [comment]
Yes, this is exactly what I meant. I agree about testing everything; I just wanted to point out where my testing stopped.

Thanks for all the work you put into this!

**Comment by toyokazu** [comment]
Thank you for your confirmation!
I merged the branch to the master and push a new gem.
I really appreciate your contribution to propose a solution to an issue.

Best Regards

**Comment by tpdownes** [comment]
@matthias-fratz I'd appreciate any thoughts you have on #19 . I am using omnibus packaging with `gitlab.rb` style configuration.
